### PR TITLE
Only update connection strings if they contained a wildcard.

### PR DESCRIPTION
**Pull request by eflumerf**

### CODE REVIEW

**Comment by eflumerf** [comment]
Resolves #50

**Comment by eflumerf** [comment]
Pinging this set of PRs.

**Comment by plasorak** [comment]
Could you explain a bit why this is needed?

**Comment by eflumerf** [comment]
If the connection string contains a wildcard, it means that ZMQ will be instructed to bind to a dynamic port number or all interfaces (`*` == `0.0.0.0`). This dynamic information must be resolved locally before being published to the ConnectivityService so that remote endpoints may connect to the correct IP and port.

**Review by plasorak — APPROVED** [review]
I'm don't think I'm able to review the changes in the unittest, changes in NetworkManager look good.

**Pull request merged**
